### ISSUE TITLE
cannot change events' height

### ISSUE THREAD

**Issue by AlexandrePlus** [ka215/jquery.timeline#42]
If options.rowHeight is changed compare to the default value, the height of the events remains unchanged.
It seems that the height of the events is based only on the "Default" options and not on the given options (it is not recalculated). It therefore remains equal to 44 = Default.rowHeight - Default.marginHeight * 2 = 48 - 2*2

https://github.com/ka215/jquery.timeline/blob/2e9de82a056744a87f3b78f0f2356130fa68ead6/src/timeline.js#L131

**Comment by ka215** [comment]
Hi there,

Thank you for telling me.
I will check and fix that by next release version at the latest.

Thank you for everything.

**Comment by rkorzeniewski** [comment]
@ka215 did you fix this issue? I'm using 2.0.0b2 and it is still there.

**Comment by ka215** [comment]
Hi there,

I fixed that bug then released version 2.0.0 beta-3.

Thank you,

**Comment by rkorzeniewski** [comment]
@ka215 Great! I'll test it asap.

**Comment by rkorzeniewski** [comment]
@ka215 Unfortunate with  2.0.0b4 I was tested it is still not working. Just take a look:

`<div class="jqtl-event-node" id="evt-123" data-uid="16d07973a7f2d8" style="left: 70px;top: 2px;width: 140px;height: 44px;color: rgb(52, 58, 64);background-color: rgb(255, 34, 34);"><div class="jqtl-event-label">Event1</div></div>
`

The computed height is 44px where parameter rowHeight: 32. The grid scales as expected.

**Comment by ka215** [comment]
Sorry for the inconvenience.

I check then revise once more.

**Comment by ka215** [comment]
I released fixed version 2.0.0 beta-5.

I would be happy if you would try to check that once more.

**Comment by ka215** [comment]
already fixed this.
